### ISSUE TITLE
Improve getting started guide

### ISSUE THREAD

**Issue by onmyflow** [vadimkim/cert-manager-webhook-hetzner#1]
I've had some issues figuring out how to get started with the webhook. It mainly was due to confusion on my side as to what a group is, and how to implement it. I was able to debug it, looking into the cert-manager logs, and then updating the helm groupName value but it wasn't very aparrent. 

Maybe one should mention more about the group configuration (helm values) and also provide a noticeable default value in the cli commands such as `--set groupName=acme.yourdomain.tld`

**Comment by garytaylor** [comment]
I have also had this issue - thank you for raising it, I was about to give up and I read this.

I also had to set the service account name - I didnt really know what I was doing, I just saw that the service account it was using was not allowed to create a resource in the api group, so I change the service name to match this and it got a stage further.

So, I have a values.yaml file and this is what it looks like

```
groupName: acme.gdtsoftwaresolutions.co.uk
certManager:
  serviceAccountName: certmanager-cert-manager
```

**Comment by onmyflow** [comment]
Yeah, glad I could help. It would be really nice though, if @Diaphteiros or @munnerz could pull this PR, so that others won't have issues like these.

**Comment by vadimkim** [comment]
Thank you for contributing! Sorry to be late
