### ISSUE TITLE
cannot deploy on kubernetes 1.22

### ISSUE THREAD

**Issue by djbobyd** [vadimkim/cert-manager-webhook-hetzner#15]
Hello,

I would like to thank you for the time creating this wonderful addon. I've been using it for the last year and a half. 
Unfortunately, I was not able to deploy the latest version after I upgraded to k8s 1.22, and I suspect that the previous  one is also not working correct.
I get the following error when trying to upgrade through helm:
`
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: [unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "APIService" in version "apiregistration.k8s.io/v1beta1", unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"]
`
I am guessing the problem is with some deprecated APIs but I haven't dug any deeper. Will you be able to have a look. 

Thanks!

**Comment by dnlsndr** [comment]
Please see if the `kubectl api-resources`command returns the required API resources. Are you running a different k8s distribution like k3s? They tend to deprecate resources much faster to keep them lean. Seems like you cert-manager is not installed or hasn't installed the necessary CRDs, can you verify that? This repo works for me even on vanilla kubernetes 1.23, so it shouldn't be a deprecation issue.

**Comment by djbobyd** [comment]
Hi, 
Thanks for your answer. I can confirm the APIs are missing, this is what is available:
`certificaterequests               cr,crs             cert-manager.io/v1                       true         CertificateRequest
certificates                      cert,certs         cert-manager.io/v1                       true         Certificate
clusterissuers                                       cert-manager.io/v1                       false        ClusterIssuer
issuers                                              cert-manager.io/v1                       true         Issuer
`

`clusterrolebindings                                  rbac.authorization.k8s.io/v1             false        ClusterRoleBinding
clusterroles                                         rbac.authorization.k8s.io/v1             false        ClusterRole
rolebindings                                         rbac.authorization.k8s.io/v1             true         RoleBinding
roles                                                rbac.authorization.k8s.io/v1             true         Role
`

I am using the latest cert-manager 1.6.1

and my k8s version is:

`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"archive", BuildDate:"2021-11-18T21:20:32Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
`

it is a vanilla cluster installed with kubeadm

**Comment by djbobyd** [comment]
Nevermind I deleted it and reinstalled. Now everything is working. I got an error when automatically deleting the service, I guess it was not automatically upgraded between k8s upgrades for some reason and was still referring something old.
