### ISSUE TITLE
Current docker image not working (but the code does)

### ISSUE THREAD

**Issue by aronwolf90** [vadimkim/cert-manager-webhook-hetzner#16]
The current docker image `zmejg/cert-manager-webhook-hetzner` does not work. I get an errors from the api that something is malformed but when I build a custom image from the current code everything works fine. So I think that the solution is just create a new image from the current code :)

For now I am using the following self build image as workaround: `aronwolf/cert-manager-webhook-hetzner`

**Comment by dnlsndr** [comment]
I'll see if I can create a github action, that deploys the container on each release/tag. @vadimkim What do you think?

**Comment by ibotty** [comment]
@vadimkim Can you publish a new version?  That would be great.

**Comment by vadimkim** [comment]
I published new version 1.1.1. @aronwolf90 I can add you as collaborator on docker hub if you with

**Comment by aronwolf90** [comment]
Thanks. Would be nice @vadimkim :)
