### ISSUE TITLE
cert-manager default service account name changed

### ISSUE THREAD

**Issue by Rhymen** [vadimkim/cert-manager-webhook-hetzner#21]
We installed the helm chart cert-manager:0.4.8 from the [bitnami](https://charts.bitnami.com/bitnami) catalog. After installing `cert-manager-webhook-hetzner` and creating the certificate issuer and certificate itself, we encountered the error:

```
cert-manager User "system:serviceaccount:cert-system:cert-manager-controller" cannot create resource "hetzner" in API group "acme.example.tld"
```

We were able to solve the problem by changing the `certManager.serviceAccountName` from `cert-manager ` to `cert-manager-controller`. It seems like the new cert-manager version changes the default service account name. Should this change be reflected in this chart?

Is this related to #12?

**Comment by vadimkim** [comment]
Released at version 1.1.1

**Comment by hxtmdev** [comment]
While it is true that [the bitnami chart uses the -controller suffix](https://github.com/bitnami/charts/blob/5e810854573264935cf9a6df6780452d67e7e784/bitnami/cert-manager/templates/_helpers.tpl#L46), the official cert-manager chart that [this repo links to](https://github.com/vadimkim/cert-manager-webhook-hetzner/blob/master/README.md?plain=1#L15) [does not include that suffix by default](https://github.com/cert-manager/cert-manager/blob/55b815364339540599ad5a77870df4d8665ef297/deploy/charts/cert-manager/templates/_helpers.tpl#L31) [as mentioned in their values.yaml](https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L98) and the [official direct manifest file](https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml) does the same on line 4448 as [it is generated from said helm chart](https://github.com/cert-manager/cert-manager/blob/master/deploy/manifests/README.md?plain=1#L9-L10).
Defaulting to some alternative chart's values seems rather surprising to me, especially when that is not the chart mentioned in the README. I had to override the default to use the official `cert-manager` repo.
Maybe it would make sense to change it back to the official default and have people that want to use alternative charts configure their values to match that? (Maybe consider opening a PR to bitnami instead unless they had a good reason to deviate?)

**Comment by Rhymen** [comment]
Yes, you are correct. This was a misunderstanding on my part. @vadimkim What are your thoughts on this? Should we revert this change? Sorry for the inconvenience.
