### ISSUE TITLE
Invalid header field

### ISSUE THREAD

**Issue by okleinschmidt** [vadimkim/cert-manager-webhook-hetzner#23]
I0428 08:35:40.512767       1 main.go:166] Added TXT record result:
I0428 08:35:40.512772       1 main.go:60] Presented txt record _acme-challenge.test.k3s.xxxx.xx.
E0428 08:38:31.478141       1 main.go:156] unable to find id for zone name `xxxx.xx`; unable to get zone info Get "https://dns.hetzner.com/api/v1/zones?name=xxxx.xx": net/http: invalid header field value "MYSECUREKEY\n" for key Auth-Api-Token
E0428 08:38:31.478173       1 main.go:164] Post "https://dns.hetzner.com/api/v1/records": net/http: invalid header field value "MYSECUREKEY\n" for key Auth-Api-Token
I0428 08:38:31.478181       1 main.go:166] Added TXT record result:
I0428 08:38:31.478185       1 main.go:60] Presented txt record _acme-challenge.test.k3s.xxxx.xx.

**Comment by dnlsndr** [comment]
Could you please doublecheck that your zone exists in hetzner and that your API key is correct? This rather seems to be a misconfiguration since hetzner did not change their API

**Comment by dnlsndr** [comment]
Also, there seems to be a newline in your API key. Please check that the config yaml does not somehow contain a newline

**Comment by okleinschmidt** [comment]
> Could you please doublecheck that your zone exists in hetzner and that your API key is correct? This rather seems to be a misconfiguration since hetzner did not change their API

I did already. I use the same data with Nginx Proxy Manager.

> Also, there seems to be a newline in your API key. Please check that the config yaml does not somehow contain a newline
Of course. I'm using k3s, the API key is a k8s secret. So yeah, I've seen the newline, but have no idea where it comes from. Thats the reason why I added this issue. :-(

**Comment by okleinschmidt** [comment]
Sorry, got it. The newline was included in the base64 encoded string. Sorry!
