### ISSUE TITLE
Feature Request: Keep old releases in Helm registry to not break existing release automations

### ISSUE THREAD

**Issue by philmtd** [vadimkim/cert-manager-webhook-hetzner#27]
Since the latest release 1.1.1 the previous release 1.1.0 is not available anymore which breaks existing release automation workflows.

It would be great if you could keep old chart versions available. Maybe you could try to use the GitHub Helm-Chart-Releaser-Action and create a dedicated Git repo for the chart, if that would make it easier for you. If you need an example, I have a similar Helm Registry hosted that way, if you want to have a look at it (https://github.com/philmtd/helm-charts/blob/main/.github/workflows/release.yaml).

**Comment by vadimkim** [comment]
@philmtd I expected something like that. Can put version 1.1.0 tgz back to gh-pages repo, but will it be enough?

**Comment by philmtd** [comment]
When I saw my pipeline fail I just updated to 1.1.1 after I saw that 1.1.0 is not available anymore, so for now my immediate issue is solved. The problem will be back with every new release, though..

**Comment by vadimkim** [comment]
@philmtd can you look, pls, if this should work?

**Comment by philmtd** [comment]
I guess that could work, yes. If you just keep adding the releases instead of replacing them it should do the trick. Thanks :)

**Comment by vadimkim** [comment]
Should be better now

**Comment by philmtd** [comment]
Yep, thanks. Both releases are listed now:

```
~ ❯ helm search repo hetzner --versions                                                   
NAME                                              	CHART VERSION	APP VERSION	DESCRIPTION
cert-manager-webhook-hetzner/cert-manager-webho...	1.1.1        	1.1.0      	Allow cert-manager to solve DNS challenges usin...
cert-manager-webhook-hetzner/cert-manager-webho...	1.1.0        	1.1.0      	Allow cert-manager to solve DNS challenges usin...
```
