### ISSUE TITLE
Collaborating

### ISSUE THREAD

**Issue by NotANormalNerd** [vadimkim/cert-manager-webhook-hetzner#3]
Hello vadimkim,

Nice work you have done here ^^. Since we were impatient we also have done the same work.
https://github.com/mecodia/cert-manager-webhook-hetzner

But we are no Go Programmers (Python really), our code quality is not yet up to standard.
The question is now if you want to collaborate. We use the webhook in production and are really interested in something either we can maintain for longer or that gets maintained for the foreseeable future.

Let me know what your plan is and in what ways you would be open for collaboration. :-)

Beste regards,

Dennis

**Comment by dgiebert** [comment]
Can you list the changes that have been made in your repository in a MR so that we can review?

**Comment by NotANormalNerd** [comment]
I think the biggest difference is, that the mecodia cert-manager has no restriction on Zones but can use all the Domains you have within Hetzner. Other than that I can't remember any difference and the code was mostly copied directly from the Hetzner Docs and slightly edited to fit our usecase.

**Comment by deyaeddin** [comment]
Hi @NotANormalNerd 
I'm not sure what you mean by "restriction on zones"? I have built a new webhook based on this repo and I have even upgraded to cert-manager 1.4.alpha1  without any restrictions on zones. I will be very happy to collaborate and maintain such a project!  I have running projects on Hetzner and I think I will keep updating for a while.

maybe we can unify our work under one repo ?! here or mecodia ...? I can push my code anywhere we can work on.

kindly check my work and let me know  
[repo](https://github.com/deyaeddin/cert-manager-webhook-hetzner)
[artifacthub](https://artifacthub.io/packages/helm/cert-manager-webhook-hetzner/cert-manager-webhook-hetzner )
