### ISSUE TITLE
publish on a different registry

### ISSUE THREAD

**Issue by ibotty** [vadimkim/cert-manager-webhook-hetzner#39]
It would be great to publish the image on another registry without draconian rate limits.  I personally like quay.io which has a nice fair use policy, but there is also the (less highly available) github package registry.

**Comment by vadimkim** [comment]
It seems it works well. Latest images are here: 
https://quay.io/repository/vadjan/cert-manager-webhook-hetzner

**Comment by ibotty** [comment]
Hi, that's great.  It works well.  Would you like me to add some github automation to automatically publish the image?  I would create a pull request adding some workflows and add the necessary secrets to the github repository.

**Comment by dgiebert** [comment]
Let me create a PR that uploads to Github and you can extend it with Quay?

**Comment by vadimkim** [comment]
> Let me create a PR that uploads to Github and you can extend it with Quay?

Thanks!

**Comment by mjtrangoni** [comment]
any news on this? We could use ghcr.io as well, which would be referenced here as well.

**Comment by vadimkim** [comment]
Repo was established and @ibotty was added as 2nd admin to test, but there are no images. I think this was due to multiple architecture support we implemented quickly. Didn't finish multi-arch for Quay's, just that. Is ghcr registry somehow better than docker hub?

**Comment by mjtrangoni** [comment]
Hi @vadimkim, the biggest problem with docker hub is that it gets rate limited.

ghcr.io is the GitHub Container Registry, and it is very handy when your project is hosted in Github, as you can perfectly link the project with the package and also link the README over there.

This is for example how it looks like, [see](https://github.com/mjtrangoni/flexlm_exporter/pkgs/container/flexlm_exporter).

Let me know if I can contribute with something here

**Comment by vadimkim** [comment]
@mjtrangoni I just merged your PR and looked into publishing routines. It seems together with changing registry I need to changes values.yaml for Helm to be able to reference registry other than i.e. "default" (docker hub). Can it brake existing deployments, what do you think?
I am planning to release all new changes we made under 1.3.0 and there new registry can be introduced

**Comment by vadimkim** [comment]
I managed to create and push new images to ghcr.io, but all different kind of architectures have no tags/lables as it was in docker hub. Check "packages". I made them public

**Comment by mjtrangoni** [comment]
ghcr.io supports multiarch already, but the GitHub Action I posted doesn't. Let me create a CI pipeline for you as PR and we can talk about it. It could also automate docker and quay.io at the same time if you want.

**Comment by vadimkim** [comment]
I read the requirements for naming secrets and it seems GITHUB_ prefix can't be used:
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions
can you rename it to GHCR, please? 
As I understand it should be variable for "actions"

**Comment by vadimkim** [comment]
It seems like everything works, but I have a feeling that forgot something :)

**Comment by mjtrangoni** [comment]
@vadimkim cool, it seems it is working now! Dont know if you still want to add `quay.io` to the registry list. Should I submit a PR?

**Comment by vadimkim** [comment]
@mjtrangoni should I change default repository value from `zmejg/cert-manager-webhook-hetzner -> ghcr.io/vadimkim/cert-manager-webhook-hetzner` in values.yaml together with README? Without it no real change will happen. Helm will continue to install from Docker hub.

**Comment by mjtrangoni** [comment]
@vadimkim #60 change the default registry to the new one here in GHCR. So after merging it, we can close this issue.

**Comment by vadimkim** [comment]
Merged
