### ISSUE TITLE
Lots of "the server could not find the requested resource" errors

### ISSUE THREAD

**Issue by bernatvadell** [vadimkim/cert-manager-webhook-hetzner#44]
I have the same problem mentioned in the issue:

https://github.com/vadimkim/cert-manager-webhook-hetzner/issues/40

In my case, it is not possible to migrate to kubernetes version 1.26 yet.

Is there any previous version compatible with this version?

Thank you!

**Comment by vadimkim** [comment]
Try to take version 1.0.0. It is the one compiled for kubernetes 1.16

**Comment by bernatvadell** [comment]
fixed using version 1.1.1

![image](https://github.com/vadimkim/cert-manager-webhook-hetzner/assets/17298604/1733ac0d-4047-42cb-8a17-46ba84e4afff)

ty!
