### ISSUE TITLE
Helm chart deployment via GitHub Actions

### ISSUE THREAD

**Issue by mjtrangoni** [vadimkim/cert-manager-webhook-hetzner#58]
Hi @vadimkim,

Now that the new image is built via GH Actions, the next stept should be deploying the current helm chart to github-pages automatically via GH actions. If you agree I can submit a PR for this as well.

**Comment by vadimkim** [comment]
I tried to do it manually now, but GH Actions is preferable way to release for sure. Please, submit PR to this issue. I will not close it unless then.

**Comment by vadimkim** [comment]
Waiting for automation PR from @mjtrangoni

**Comment by mjtrangoni** [comment]
@vadimkim PR is ready for first review. Thank you!

**Comment by vadimkim** [comment]
Looks very nice
