### ISSUE TITLE
unable to get secret `cert-manager`

### ISSUE THREAD

**Issue by Jannik-Hm** [vadimkim/cert-manager-webhook-hetzner#67]
I installed cert-manager via helm, as well as this hetzner webhook.

I can generate self signed certificates but fail the dns-01 challenge.

The corresponding cert-manager pod logs this:
```controller.go:167] "re-queuing item due to error processing" err="unable to get secret `cert-manager`; unable to find hetzner dns zone with: my-tld.com" logger="cert-manager.challenges"```

my-tld.com is btw. only a placeholder for my domain.

I verified the API-Key and zone via Insomnia (like Postman) and was able to create a TXT Record via an API Request.

I don't even know where it's getting the secret "cert-manager" from. I used the default hetzner-secret from the ReadMe.

Anybody got an idea?

**Comment by Jannik-Hm** [comment]
Nvm for some reason, coredns appended one of my search entries to *every* request and therefore the web hook was unable to reach hetzner ugh...

**Comment by Jannik-Hm** [comment]
Hey, my coredns looked up everything in my host resolv.conf and the hostname used the same tld so that there was search entry for my domain and as I've set it up as a wildcard, everything got found as a subdomain of mine.

My quick fix: remove the search entry from the host resolv.conf

I don't know if this might fix your issue too.

**Comment by rogeriolino** [comment]
@Jannik-Hm how did you debug it? I'm facing the same error message for wildcard cert. Tried to remove the `search` entry from `resolv.conf` but with no luck.
