### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by dnlsndr** [vadimkim/cert-manager-webhook-hetzner#8]
Since this repository is pretty well tested and experiences hardly any issues, I think it's safe to assume that we should introduce a semver release system. Should we kick off a release v0.1.0?

**Comment by vadimkim** [comment]
do I need to build and publish on gh-pages branch?

**Comment by dgiebert** [comment]
How about we add something like this Github Action: https://github.com/helm/chart-releaser-action

**Comment by onmyflow** [comment]
Sounds great! It'll make chart and container deployments much easier. Seems that you @dgiebert have experience with implementing things like that? Maybe you could create a PR, otherwise I'll try my luck :)

**Comment by vadimkim** [comment]
Yes, I also a bit stuck here due to lack of experience. Need to read and try first...

**Comment by dgiebert** [comment]
If you are fine with it I can prepare something, probably this weekend :+1:

**Comment by tarioch** [comment]
would be great to get a new release, I guess it should be 1.1.0 (as the chart currently is at 1.0.0, especially also now that kubernetes 1.22 is out, the fixes for #4 would be great (as far as I see they have been fixed in master)

**Comment by vadimkim** [comment]
@tarioch do you mean to update gh-pages branch with new release binary with new version?

**Comment by tarioch** [comment]
yes and change the version in chart.yaml to 1.1.0 so that it's recognized as a new version

**Comment by vadimkim** [comment]
Released as 1.1.0. Sorry for the delay - forgot how to do it
